### ISSUE TITLE
Is this AMF completely fault-tolerant ?

### ISSUE THREAD

**Issue by dark-astra** [omec-project/amf#283]
The 5G UE Registration call flow consists of multiple exchange of Uplink and Downlink Transport Messages. So if the AMF pod fails at some stage between these message exchanges, will the UE registration fail and restart a new registration request with the new AMF or can the UE resume the registration at the very step where it failed,  with the new AMF ?

I see you are saving the context in MongoDB, but I wanted to know, is the statelessness procedural, where after the registration procedure, the context is saved or is it saved after each message exchange with RAN all along the the registration procedure, so that the registration, need not be started from the beginning if it fails, somewhere in between ?

I did a simple experiment to test this:

I installed the SDCore using Aether OnRamp and configured the gnbsim to run REGISTRATION procedure for 10 UEs.
So when the gnbsim starts sending request, I delete the AMF pod, and this cause the registrations to fail.

```bash
ok: [node1] => {
"gNbsimPod.stdout_lines": [
"time="2024-08-18T17:50:22Z" level=info msg="Profile Name: profile1 , Profile Type: register" category=Summary component=GNBSIM",
"time="2024-08-18T17:50:22Z" level=info msg="Ue's Passed: 6 , Ue's Failed: 4" category=Summary component=GNBSIM",
"time="2024-08-18T17:50:22Z" level=info msg="Profile Errors:" category=Summary component=GNBSIM",
"time="2024-08-18T17:50:22Z" level=error msg="imsi
, profile timeout" category=Summary component=GNBSIM",
"time="2024-08-18T17:50:22Z" level=error msg="imsi
, profile timeout" category=Summary component=GNBSIM",
"time="2024-08-18T17:50:22Z" level=error msg="imsi
, profile timeout" category=Summary component=GNBSIM",
"time="2024-08-18T17:50:22Z" level=error msg="imsi
, profile timeout" category=Summary component=GNBSIM",
"time="2024-08-18T17:50:22Z" level=info msg="Profile Status: FAIL" category=Summary component=GNBSIM"
]
}
```

My gnbsim-default.yaml looks like the following:

```yaml
profiles:

profileType: register # UE Registration
profileName: profile1
enable: true
gnbName: gnb1
execInParallel: false
startImsi: 208930100007487
ueCount: 10
defaultAs: "192.168.250.1"
perUserTimeout: 10
plmnId:
mcc: 208
mnc: 93
opc: "981d464c7c52eb6e5036234984ad0bcf"
key: "5122250214c33e723a5dd523fc145fc0"
sequenceNumber: "16f3b3f70fc2"
```
